# Generated by Django 5.2.1 on 2025-05-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('tech', 'Technology'), ('finance', 'Finance'), ('health', 'Healthcare'), ('education', 'Education')], max_length=50)),
                ('company_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('lagos', 'Lagos'), ('abuja', 'Abuja'), ('rivers', 'Rivers')], max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('tax_id', models.CharField(max_length=100)),
            ],
        ),
    ]
